apiVersion: v1
kind: ConfigMap
metadata:
  name: ev-system-config
  namespace: ev-system
  labels:
    app.kubernetes.io/name: ev-system
data:
  NODE_ENV: "production"
  FRONTEND_URL: "http://frontend:3000"
  VITE_API_URL: "/api"
  AUTH_SERVICE_URL: "http://auth-service:5001"
  EV_SERVICE_URL: "http://ev-service:5002"
  STATION_SERVICE_URL: "http://station-service:5003"
  BOOKING_SERVICE_URL: "http://booking-service:5004"
  DECISION_SERVICE_URL: "http://decision-service:5005"
  CHARGING_SERVICE_URL: "http://charging-service:5006"
  PAYMENT_SERVICE_URL: "http://payment-service:5007"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5008"
  ANALYTICS_SERVICE_URL: "http://analytics-service:5009"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
