apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-service
  namespace: ev-system
  labels:
    app: ev-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ev-service
  template:
    metadata:
      labels:
        app: ev-service
    spec:
      containers:
        - name: ev-service
          image: autonomous-ev/ev-service:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ev-system-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ev-system-secrets
                  key: MONGO_URI_EV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ev-system-secrets
                  key: JWT_SECRET
            - name: INTERNAL_KEY
              valueFrom:
                secretKeyRef:
                  name: ev-system-secrets
                  key: INTERNAL_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ev-service
  namespace: ev-system
  labels:
    app: ev-service
spec:
  type: ClusterIP
  selector:
    app: ev-service
  ports:
    - port: 5002
      targetPort: 5002
