apiVersion: v1
kind: Secret
metadata:
  name: ev-system-secrets
  namespace: ev-system
  labels:
    app.kubernetes.io/name: ev-system
type: Opaque
data:
  # Base64 encoded dummy values for development/manifest demonstration
  # JWT_SECRET: "c3VwZXJzZWNyZXRqd3RrZXlfZXZfMjAyNl9jaGFuZ2VfaW5fcHJvZA=="
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RrZXlfZXZfMjAyNl9jaGFuZ2VfaW5fcHJvZA==
  # INTERNAL_KEY: "aW50ZXJuYWxfc2VjcmV0X2tleV8yMDI2X2V2X3N5c3RlbQ=="
  INTERNAL_KEY: aW50ZXJuYWxfc2VjcmV0X2tleV8yMDI2X2V2X3N5c3RlbQ==
  # Mongo URIs per service
  MONGO_URI_AUTH: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYXV0aF9kYg==
  MONGO_URI_EV: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZXZfZGI=
  MONGO_URI_STATION: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvc3RhdGlvbl9kYg==
  MONGO_URI_BOOKING: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYm9va2luZ19kYg==
  MONGO_URI_CHARGING: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvY2hhcmdpbmdfZGI=
  MONGO_URI_PAYMENT: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcGF5bWVudF9kYg==
  MONGO_URI_NOTIFICATION: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvbm90aWZpY2F0aW9uX2Ri
  MONGO_URI_ANALYTICS: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYW5hbHl0aWNzX2Ri
