const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const authService = require('../src/services/authService');
const User = require('../src/models/User');
const { authenticate } = require('../src/middleware/auth');

// Mock User model methods to ensure tests run fast and isolated
jest.mock('../src/models/User');

describe('Auth Service & Security Tests', () => {
  const JWT_SECRET = process.env.JWT_SECRET || 'supersecretjwtkey_ev_2026_change_in_prod';

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('1. Token Generation & Template Middleware Compatibility', () => {
    test('Token generated by authService is accepted by _template auth middleware', () => {
      const mockUser = {
        userId: 'U101',
        role: 'USER',
        email: 'test@ev.com'
      };

      const token = authService.generateToken(mockUser);
      expect(typeof token).toBe('string');

      // Verify token with JWT secret
      const decoded = jwt.verify(token, JWT_SECRET);
      expect(decoded.userId).toBe('U101');
      expect(decoded.role).toBe('USER');
      expect(decoded.email).toBe('test@ev.com');

      // Test with _template auth middleware
      const req = {
        headers: {
          authorization: `Bearer ${token}`
        }
      };
      const res = {
        status: jest.fn().mockReturnThis(),
        json: jest.fn()
      };
      const next = jest.fn();

      authenticate(req, res, next);
      expect(next).toHaveBeenCalled();
      expect(req.user).toBeDefined();
      expect(req.user.userId).toBe('U101');
    });

    test('_template auth middleware rejects invalid token', () => {
      const req = {
        headers: {
          authorization: 'Bearer invalid.token.payload'
        }
      };
      const res = {
        status: jest.fn().mockReturnThis(),
        json: jest.fn()
      };
      const next = jest.fn();

      authenticate(req, res, next);
      expect(next).not.toHaveBeenCalled();
      expect(res.status).toHaveBeenCalledWith(401);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
          success: false,
          message: 'Invalid or expired token'
        })
      );
    });
  });

  describe('2. User Registration', () => {
    test('Registers a new user and forces role to USER per RULEBOOK', async () => {
      User.findOne.mockResolvedValue(null);

      const fakeUserDoc = {
        userId: 'U102',
        name: 'Alice Green',
        email: 'alice@ev.com',
        role: 'USER',
        toJSON: () => ({
          userId: 'U102',
          name: 'Alice Green',
          email: 'alice@ev.com',
          role: 'USER'
        })
      };
      User.create.mockResolvedValue(fakeUserDoc);

      const result = await authService.register({
        name: 'Alice Green',
        email: 'alice@ev.com',
        password: 'Password@123'
      });

      expect(result).toHaveProperty('user');
      expect(result).toHaveProperty('token');
      expect(result.user.role).toBe('USER');
      expect(result.user.email).toBe('alice@ev.com');
      expect(User.create).toHaveBeenCalledWith(
        expect.objectContaining({
          role: 'USER',
          email: 'alice@ev.com'
        })
      );
    });

    test('Rejects duplicate email registration with 409 status', async () => {
      User.findOne.mockResolvedValue({ email: 'alice@ev.com' });

      await expect(
        authService.register({
          name: 'Alice Green',
          email: 'alice@ev.com',
          password: 'Password@123'
        })
      ).rejects.toMatchObject({
        status: 409,
        message: 'Email is already registered'
      });
    });

    test('Validates required fields on registration', async () => {
      await expect(
        authService.register({ name: 'Alice', email: '' })
      ).rejects.toMatchObject({
        status: 400
      });
    });
  });

  describe('3. User Login', () => {
    test('Logs in successfully with matching password and returns token', async () => {
      const hashedPassword = await bcrypt.hash('Secret@123', 10);
      const fakeUserDoc = {
        userId: 'U101',
        name: 'Bob',
        email: 'bob@ev.com',
        password: hashedPassword,
        role: 'USER',
        toJSON: () => ({
          userId: 'U101',
          name: 'Bob',
          email: 'bob@ev.com',
          role: 'USER'
        })
      };

      User.findOne.mockResolvedValue(fakeUserDoc);

      const result = await authService.login({
        email: 'bob@ev.com',
        password: 'Secret@123'
      });

      expect(result).toHaveProperty('user');
      expect(result).toHaveProperty('token');
      expect(result.user.userId).toBe('U101');
    });

    test('Rejects login with invalid password with 401 status', async () => {
      const hashedPassword = await bcrypt.hash('CorrectPassword', 10);
      const fakeUserDoc = {
        email: 'bob@ev.com',
        password: hashedPassword
      };

      User.findOne.mockResolvedValue(fakeUserDoc);

      await expect(
        authService.login({
          email: 'bob@ev.com',
          password: 'WrongPassword'
        })
      ).rejects.toMatchObject({
        status: 401,
        message: 'Invalid email or password'
      });
    });

    test('Rejects login with non-existent email with 401 status', async () => {
      User.findOne.mockResolvedValue(null);

      await expect(
        authService.login({
          email: 'nonexistent@ev.com',
          password: 'SomePassword'
        })
      ).rejects.toMatchObject({
        status: 401,
        message: 'Invalid email or password'
      });
    });
  });

  describe('4. User Profile Retrieval', () => {
    test('Retrieves user profile without password', async () => {
      const fakeUserDoc = {
        userId: 'U101',
        name: 'Bob',
        email: 'bob@ev.com',
        role: 'USER',
        toJSON: () => ({
          userId: 'U101',
          name: 'Bob',
          email: 'bob@ev.com',
          role: 'USER'
        })
      };

      User.findOne.mockResolvedValue(fakeUserDoc);

      const profile = await authService.getProfile('U101');
      expect(profile.userId).toBe('U101');
      expect(profile).not.toHaveProperty('password');
    });

    test('Returns 404 when profile user does not exist', async () => {
      User.findOne.mockResolvedValue(null);

      await expect(authService.getProfile('UNKNOWN')).rejects.toMatchObject({
        status: 404,
        message: 'User not found'
      });
    });
  });
});
